version: "3.8"

services:
  nginx:
    container_name: learn_nginx
    volumes:
      - ./..:/var/www/learn
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
    networks:
      - backend_net
    build:
      context: ./..
      target: nginx
      dockerfile: docker/Dockerfile

networks:
  backend_net: